version: "3.8"

services:   
  prod:
    image: ocrpytesseract/ocrpytesseract:latest-prod
    working_dir: /production/ocrpytesseract
    entrypoint: uvicorn main:app --reload --port 80 --host 0.0.0.0
    build: 
      target: production
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:80